### ISSUE TITLE
Style does not apply on first plot

### ISSUE THREAD

**Issue by guibaq** [quantumblacklabs/qbstyles#1]
I followed global installation instruction. The styles do not apply on the first plot I run. I need to re-run `plt.style.use(['qb-common', 'qb-dark'])` for it to work.

![image](https://user-images.githubusercontent.com/43790464/55803163-b69e4080-5ad1-11e9-8518-fd38b9d7bde8.png)

**Comment by tsanikgr** [comment]
Please see the README. You must `import matplotlib` and run `plt.style.use([...])` in different cells :)
